In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(sparse_output=False)

In [ ]:
df = pd.DataFrame({
    'Gender': ['Male','Female','Female','Male'],
    'Education': ['UG','PG','School','UG'],
    'City': ['Delhi','Mumbai','Delhi','Kolkata']
})

In [ ]:
df

   Gender Education     City
0    Male        UG    Delhi
1  Female        PG   Mumbai
2  Female    School    Delhi
3    Male        UG  Kolkata

In [ ]:
ohe.fit_transform(df[['Gender','City']])

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [ ]:
# Which feature is divided into 0/1s
ohe.feature_names_in_

array(['Gender', 'City'], dtype=object)

In [ ]:
# All sub-features of the main-feature
ohe.categories_

[array(['Female', 'Male'], dtype=object),
 array(['Delhi', 'Kolkata', 'Mumbai'], dtype=object)]

In [ ]:
# All sub-features_main-feature present
ohe.get_feature_names_out()

array(['Gender_Female', 'Gender_Male', 'City_Delhi', 'City_Kolkata',
       'City_Mumbai'], dtype=object)

In [ ]:
# Entire 0/1 Matrix
pd.DataFrame(ohe.fit_transform(df[['Gender','City']]),columns=ohe.get_feature_names_out())

   Gender_Female  Gender_Male  City_Delhi  City_Kolkata  City_Mumbai
0            0.0          1.0         1.0           0.0          0.0
1            1.0          0.0         0.0           0.0          1.0
2            1.0          0.0         1.0           0.0          0.0
3            0.0          1.0         0.0           1.0          0.0

In [ ]:
# 0/1s to categorical
ohe.inverse_transform([[0,1,0,1,0]])

array([['Male', 'Kolkata']], dtype=object)

# 🎯 Dummy Variable Trap

In [ ]:
ohe1 = OneHotEncoder(sparse_output=False,drop='first')

In [ ]:
df['City'].unique()

array(['Delhi', 'Mumbai', 'Kolkata'], dtype=object)

In [ ]:
ohe1.fit_transform(df[['City']])

array([[0., 0.],
       [0., 1.],
       [0., 0.],
       [1., 0.]])

In [ ]:
ohe1.feature_names_in_

array(['City'], dtype=object)

In [ ]:
ohe1.categories_

[array(['Delhi', 'Kolkata', 'Mumbai'], dtype=object)]

In [ ]:
# City_Delhi is dropped
ohe1.get_feature_names_out()

array(['City_Kolkata', 'City_Mumbai'], dtype=object)

In [ ]:
pd.DataFrame(ohe1.fit_transform(df[['City']]),columns=ohe1.get_feature_names_out())

   City_Kolkata  City_Mumbai
0           0.0          0.0
1           0.0          1.0
2           0.0          0.0
3           1.0          0.0

# 🎯 Handling Infrequent Categories

In [ ]:
# max_categry  = ...
# min_frquency = ...

# 🎯 Handling Unknown

In [ ]:
# ohe = OneHotEncoder(..., handle_unknown = 'ignore', ...)

In [ ]:
df = pd.DataFrame({
    'Gender': ['Male','Female','Female','Male'],
    'Education': ['UG','PG','School','UG'],
    'City': ['Delhi','Mumbai','Delhi','Kolkata']
})

In [ ]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown ='ignore')

In [ ]:
# Entire 0/1 Matrix
pd.DataFrame(ohe.fit_transform(df[['Gender','City']]),columns=ohe.get_feature_names_out())

   Gender_Female  Gender_Male  City_Delhi  City_Kolkata  City_Mumbai
0            0.0          1.0         1.0           0.0          0.0
1            1.0          0.0         0.0           0.0          1.0
2            1.0          0.0         1.0           0.0          0.0
3            0.0          1.0         0.0           1.0          0.0

In [ ]:
ohe.inverse_transform(np.array([0,1,1,0,0]).reshape(1,5))

array([['Male', 'Delhi']], dtype=object)

In [ ]:
ohe.transform(np.array([['Male','Delhi']]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 1., 1., 0., 0.]])

In [ ]:
#‘ignore’ : When an unknown category is encountered
# one-hot encoded columns for this feature will be all zeros
ohe.transform(np.array([['DLFJOERJGROG', 'Kolkata']]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 0., 1., 0.]])