In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('customer.csv')

In [ ]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [ ]:
df.drop(columns=['gender', 'age'], inplace=True)

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [ ]:
df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [ ]:
df.head(2)

    review education purchased
0  Average    School        No
1     Poor        UG        No

In [ ]:
X = df.iloc[:,:2]
y = df.iloc[:,-1]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
X_train.iloc[8]

review         Good
education    School
Name: 18, dtype: object

# 🎯 OrdinalEncoder

### OrdinalEncoder(categories = [ ])

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
# order of elements in list should be maintained as per data

In [ ]:
X_train_transformed = oe.fit_transform(X_train)
X_test_transformed = oe.transform(X_test)

In [ ]:
X_train_transformed[8]

array([2., 0.])

# 🎯 OrdinalEncoder Special Functions

### oe.categories_, oe.get_feature_names_out()

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [ ]:
oe.get_feature_names_out()

array(['review', 'education'], dtype=object)

# 🎯 Handling Unknown Values

###OrdinalEncoder (categories=[ ], handle_unknown = 'use_encoded_value' , unkonwn_value = ... )

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']],
                    handle_unknown='use_encoded_value',
                    unknown_value=-1)
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)
X_train_2 = oe.fit_transform(X_train)
oe.transform(np.array(['Poor','college']).reshape(1,2))
# If multiple unknown categories appear, OrdinalEncoder
# assigns the same unknown_value to all of them, because it
# treats them as a single unseen category group.

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[ 0., -1.]])

# 🎯 Handling Infrequent Categories

###OrdinalEncoder (max_categories = ...)
###OrdinalEncoder (min_fequency = ...)

In [ ]:
# handling infrequent categories
X = np.array([['dog'] * 5 + ['cat'] * 20 + ['rabbit'] * 10 +['snake'] * 3 + ['horse'] * 2], dtype=object).T
X

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

Approach 1 : Explicitly Declaring no. of Categories

In [ ]:
enc = OrdinalEncoder(max_categories=3).fit(X)

In [ ]:
enc.categories_

[array(['cat', 'dog', 'horse', 'rabbit', 'snake'], dtype=object)]

In [ ]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [ ]:
enc.transform(np.array([['cat','rabbit','snake','dog','horse']]).reshape(5,1))

array([[0.],
       [1.],
       [2.],
       [2.],
       [2.]])

Approach 2 : Frequency Count

In [ ]:
enc = OrdinalEncoder(min_frequency=5).fit(X)

In [ ]:
enc.infrequent_categories_

[array(['horse', 'snake'], dtype=object)]

In [ ]:
enc.transform(np.array([['cat','dog','rabbit','snake','horse']]).reshape(5,1))

array([[0.],
       [1.],
       [2.],
       [3.],
       [3.]])

#🎯 Handling Missing Values

### OrdinalEncoder (encoded_missing_value=-1)

In [ ]:
# Example categorical data with missing values
data = [['Cat'], [np.nan], ['Dog'], ['Fish'], [np.nan]]
encoder = OrdinalEncoder(encoded_missing_value=-1)
encoded_data = encoder.fit_transform(data)
print(encoded_data)

[[ 0.]
 [-1.]
 [ 1.]
 [ 2.]
 [-1.]]